from ConsoleTiles import ConsoleTiles
class WindowsTiles(ConsoleTiles):
    #STATIC CLASS.  NO INSTANCES.
    vwall="\xb3"
    hwall="\xc4"
    wall_corner_nw="\xda"
    wall_corner_ne="\xbf"
    wall_corner_sw="\xc0"
    wall_corner_se="\xd9"
    wall_TeeJnc_up="\xc1"
    wall_TeeJnc_dn="\xc2"
    wall_TeeJnc_rt="\xc3"
    wall_TeeJnc_lt="\xb4"
    wall_cross="\xc5"
    user="\x01"
    fred="\x02"
    ron="\x02"
    hermione="\x02"
    quirrel="\x02"
    crabbe="\x02"
    goyle="\x02"
    quirrel="\x02"
    sprout="\x02"
    snape="\x02"
    filtch="\x02"
    dumbledore="\x02"
    extra="\x02"

