"""From PostSortingLevel docstring: "Not to be taken seriously, this is an attempted reimplementation of the opening of Electronic Arts' Harry Potter and the Philosopher's Stone.  This is not intended for release or completion."

These tiles were drafted up back when I actually intended to reimplement the entire game (although not to distribute it).  This shall not happen any time soon, at least until shooting is implemented (shooting, firing, zapping all use basically the same mechanism which is not implemented at present).
"""
from repugeng.ConsoleTiles import ConsoleTiles
class HarryPotterTiles(ConsoleTiles):
    fred="@"
    ron="@"
    hermione="@"
    quirrel="@"
    peeves="P"
    malfoy="M"
    crabbe="@"
    goyle="@"
    quirrel="@"
    gnome="G"
    flitwick="@"
    snail="S"
    tentacula="T"
    tentacle="~"
    sprout="@"
    sprout="\x02"
    bush="B"
    needle="~"
    chest="]"
    cauldron=")"
    doxy="D"
    snare="s"
    boulder="O"
    snape="@"
    filtch="@"
    norris="&"
    fluffyhead="+"
    erised="}"
    dumbledore="@"
    card='"'
    frog="f"
    extra="@"
    drink="!"
    bean="'"
    ingredient="%"

#Windows-specific tiles which shall be added once the expansion
#system supports them somehow.
"""
    fred="\x02"
    ron="\x02"
    hermione="\x02"
    quirrel="\x02"
    crabbe="\x02"
    goyle="\x02"
    quirrel="\x02"
    sprout="\x02"
    snape="\x02"
    filtch="\x02"
    dumbledore="\x02"
    extra="\x02"
"""
